#!/usr/bin/env bash
set -euo pipefail

ROOT=""
VARIANT=""

usage() {
  cat <<'EOF'
check_scaffold_output_contract.sh

Validates a scaffolded project output for key invariants that should hold for
projects generated by `scaffold_research_workflow.sh`.

Usage:
  bash scripts/dev/check_scaffold_output_contract.sh --root <project_root> [--variant full|minimal]

Checks (fast, deterministic):
  - required files/dirs exist
  - sed placeholders <PROJECT_NAME>/<PROJECT_ROOT>/<PROFILE> are fully substituted
  - for variant=full: scaffolded wrapper scripts are executable and syntactically valid
  - for variant=full: wrappers use SKILL_DIR indirection (no hard-coded ~/.codex/skills/... paths)
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --root) ROOT="${2:-}"; shift 2 ;;
    --variant) VARIANT="${2:-}"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

if [[ -z "${ROOT}" ]]; then
  echo "ERROR: --root is required" >&2
  usage
  exit 2
fi
if [[ ! -d "${ROOT}" ]]; then
  echo "ERROR: root dir not found: ${ROOT}" >&2
  exit 2
fi

infer_variant() {
  local cfg="${ROOT}/research_team_config.json"
  if [[ ! -f "${cfg}" ]]; then
    echo "minimal"
    return 0
  fi
  python3 - "${cfg}" <<'PY' || echo "minimal"
from __future__ import annotations
import json
import sys
from pathlib import Path
path = Path(sys.argv[1])
try:
    data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
except Exception:
    print("minimal")
    raise SystemExit(0)
v = str((data or {}).get("scaffold_variant", "")).strip().lower()
if v in ("minimal", "full"):
    print(v)
else:
    print("minimal")
PY
}

if [[ -z "${VARIANT}" ]]; then
  VARIANT="$(infer_variant)"
fi
case "${VARIANT}" in
  full|minimal) ;;
  *)
    echo "ERROR: invalid --variant: ${VARIANT} (expected full|minimal)" >&2
    exit 2
    ;;
esac

require_paths=(
  "research_notebook.md"
  "research_contract.md"
  "project_charter.md"
  "research_plan.md"
  "project_index.md"
  ".mcp.template.json"
)

for rel in "${require_paths[@]}"; do
  if [[ ! -f "${ROOT}/${rel}" ]]; then
    echo "ERROR: missing required file: ${ROOT}/${rel}" >&2
    exit 1
  fi
done

require_dirs=(
  "artifacts"
  "artifacts/runs"
  "docs"
  "specs"
)
for rel in "${require_dirs[@]}"; do
  if [[ ! -d "${ROOT}/${rel}" ]]; then
    echo "ERROR: missing required dir: ${ROOT}/${rel}" >&2
    exit 1
  fi
done

echo "[check] placeholder substitution"
patterns="(<PROJECT_NAME>|<PROJECT_ROOT>|<PROFILE>)"
if command -v rg >/dev/null 2>&1; then
  if rg -n --hidden --no-ignore-vcs -S "${patterns}" "${ROOT}" \
      -g'*.md' -g'*.txt' -g'*.json' -g'*.sh' \
      -g'!**/.git/**' -g'!**/team/runs/**' -g'!**/artifacts/runs/**' >/dev/null; then
    echo "ERROR: found unsubstituted scaffold placeholders under: ${ROOT}" >&2
    rg -n --hidden --no-ignore-vcs -S "${patterns}" "${ROOT}" \
      -g'*.md' -g'*.txt' -g'*.json' -g'*.sh' \
      -g'!**/.git/**' -g'!**/team/runs/**' -g'!**/artifacts/runs/**' >&2 || true
    exit 1
  fi
else
  # Fallback: grep cannot filter globs reliably; keep scope narrow via find.
  matches=""
  while IFS= read -r -d '' f; do
    if grep -nE "${patterns}" "${f}" >/dev/null 2>&1; then
      matches="yes"
      echo "MATCH: ${f}" >&2
      grep -nE "${patterns}" "${f}" >&2 || true
    fi
  done < <(find "${ROOT}" -type f \( -name '*.md' -o -name '*.txt' -o -name '*.json' -o -name '*.sh' \) -print0)
  if [[ -n "${matches}" ]]; then
    echo "ERROR: found unsubstituted scaffold placeholders under: ${ROOT}" >&2
    exit 1
  fi
fi

if [[ "${VARIANT}" == "full" ]]; then
  full_paths=(
    "research_preflight.md"
    "project_brief.md"
    "idea_log.md"
    "research_team_config.json"
    "prompts/_team_packet.txt"
    "prompts/_system_member_a.txt"
    "prompts/_system_member_b.txt"
    "knowledge_base/README.md"
    "knowledge_base/methodology_traces/_template.md"
    "knowledge_base/methodology_traces/literature_queries.md"
    "knowledge_graph/README.md"
    "knowledge_graph/claims.jsonl"
    "knowledge_graph/edges.jsonl"
    "knowledge_graph/evidence_manifest.jsonl"
    "mechanisms/00_pre_task_clarifier.md"
    "mechanisms/01_analogy_mining.md"
    "mechanisms/02_problem_framing_protocol.md"
  )
  full_dirs=(
    "team"
    "team/runs"
    "references"
    "knowledge_base/literature"
    "knowledge_base/priors"
    "knowledge_graph"
    "mechanisms"
  )
  for rel in "${full_paths[@]}"; do
    if [[ ! -f "${ROOT}/${rel}" ]]; then
      echo "ERROR: missing full-scaffold file: ${ROOT}/${rel}" >&2
      exit 1
    fi
  done
  for rel in "${full_dirs[@]}"; do
    if [[ ! -d "${ROOT}/${rel}" ]]; then
      echo "ERROR: missing full-scaffold dir: ${ROOT}/${rel}" >&2
      exit 1
    fi
  done

  wrappers=(
    "scripts/run_full_cycle.sh"
    "scripts/run_autopilot.sh"
    "scripts/export_paper_bundle.sh"
    "scripts/run_claude.sh"
    "scripts/run_gemini.sh"
    "scripts/execute_task.sh"
  )

  echo "[check] wrapper scripts (exec bit + bash -n)"
  for rel in "${wrappers[@]}"; do
    path="${ROOT}/${rel}"
    if [[ ! -f "${path}" ]]; then
      echo "ERROR: missing wrapper script: ${path}" >&2
      exit 1
    fi
    if [[ ! -x "${path}" ]]; then
      echo "ERROR: wrapper script is not executable: ${path}" >&2
      exit 1
    fi
    bash -n "${path}"
  done

  echo "[check] wrappers use SKILL_DIR indirection"
  skill_wrappers=(
    "scripts/run_full_cycle.sh"
    "scripts/run_autopilot.sh"
    "scripts/export_paper_bundle.sh"
  )
  for rel in "${skill_wrappers[@]}"; do
    path="${ROOT}/${rel}"
    if command -v rg >/dev/null 2>&1; then
      if ! rg -q 'SKILL_DIR=' "${path}"; then
        echo "ERROR: expected SKILL_DIR=... in wrapper: ${path}" >&2
        exit 1
      fi
      if rg -q "~/.codex/skills/" "${path}"; then
        echo "ERROR: wrapper hard-codes a home-directory skill path (expected SKILL_DIR): ${path}" >&2
        exit 1
      fi
    else
      if ! grep -q 'SKILL_DIR=' "${path}"; then
        echo "ERROR: expected SKILL_DIR=... in wrapper: ${path}" >&2
        exit 1
      fi
      if grep -q "~/.codex/skills/" "${path}"; then
        echo "ERROR: wrapper hard-codes a home-directory skill path (expected SKILL_DIR): ${path}" >&2
        exit 1
      fi
    fi
  done
else
  forbidden_paths=(
    "prompts"
    "research_team_config.json"
    "knowledge_base"
    "references"
    "team"
    ".hep"
  )
  for rel in "${forbidden_paths[@]}"; do
    if [[ -e "${ROOT}/${rel}" ]]; then
      echo "ERROR: minimal scaffold should not precreate optional path: ${ROOT}/${rel}" >&2
      exit 1
    fi
  done
fi

echo "[ok] scaffold output contract checks passed: ${ROOT} (variant=${VARIANT})"
