#!/usr/bin/env bash
set -euo pipefail

WORKSPACE=""
PROJECT="research-team-skilldev"
PROFILE="methodology_dev"
TAG="SKILLDEV-M0"
STAGE="development"
RESET=0
SKIP_DEMO=0
FORCE_SCAFFOLD=0

usage() {
  cat <<'EOF'
init_skilldev_workspace.sh

Create/update a local "skilldev" workspace for developing this skill using its own workflow.

Defaults:
  - workspace: <skill_root>/skilldev
  - project: research-team-skilldev
  - profile: methodology_dev
  - stage: development
  - tag: SKILLDEV-M0

Usage:
  bash scripts/dev/init_skilldev_workspace.sh [--workspace PATH] [--reset] [--stage exploration|development|publication]

Options:
  --workspace PATH        Workspace directory (default: <skill_root>/skilldev)
  --project NAME          Project name used for scaffold placeholder replacement
  --profile PROFILE       theory_only|numerics_only|mixed|exploratory|literature_review|methodology_dev|toolkit_extraction|custom
  --stage STAGE           exploration|development|publication (default: development)
  --tag TAG               Demo milestone tag (default: SKILLDEV-M0)
  --reset                 Delete workspace and recreate (requires marker file)
  --force-scaffold         Overwrite existing scaffold files (dangerous; for refresh)
  --skip-demo             Do not generate the deterministic demo milestone
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace) WORKSPACE="${2:-}"; shift 2 ;;
    --project) PROJECT="${2:-}"; shift 2 ;;
    --profile) PROFILE="${2:-}"; shift 2 ;;
    --stage) STAGE="${2:-}"; shift 2 ;;
    --tag) TAG="${2:-}"; shift 2 ;;
    --reset) RESET=1; shift ;;
    --force-scaffold) FORCE_SCAFFOLD=1; shift ;;
    --skip-demo) SKIP_DEMO=1; shift ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2 ;;
  esac
done

case "${STAGE}" in
  exploration|development|publication) ;;
  *)
    echo "ERROR: invalid --stage: ${STAGE} (expected exploration|development|publication)" >&2
    exit 2
    ;;
esac

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

if [[ -z "${WORKSPACE}" ]]; then
  WORKSPACE="${SKILL_ROOT}/skilldev"
fi

MARKER="${WORKSPACE}/.research_team_skilldev_workspace"

if [[ "${RESET}" -eq 1 ]]; then
  if [[ -d "${WORKSPACE}" ]]; then
    if [[ ! -f "${MARKER}" ]]; then
      echo "ERROR: refusing to delete workspace without marker file: ${MARKER}" >&2
      echo "Hint: delete it manually if you are sure, or recreate once to generate the marker." >&2
      exit 2
    fi
    rm -rf "${WORKSPACE}"
  fi
fi

scaffold_args=( --root "${WORKSPACE}" --project "${PROJECT}" )
if [[ -n "${PROFILE}" ]]; then
  scaffold_args+=( --profile "${PROFILE}" )
fi
if [[ "${FORCE_SCAFFOLD}" -eq 1 ]]; then
  scaffold_args+=( --force )
fi

bash "${SKILL_ROOT}/scripts/bin/scaffold_research_workflow.sh" "${scaffold_args[@]}"

# Refresh project-local wrapper scripts that delegate back to the skill, even if they already exist.
# This keeps the skilldev workspace aligned when assets change (without forcing a full scaffold overwrite).
wrapper_refresh=(
  "run_full_cycle.sh"
  "run_autopilot.sh"
  "export_paper_bundle.sh"
)
for f in "${wrapper_refresh[@]}"; do
  src="${SKILL_ROOT}/assets/${f}"
  dst="${WORKSPACE}/scripts/${f}"
  if [[ -f "${dst}" && -f "${src}" ]]; then
    if grep -q "~/.codex/skills/research-team" "${dst}" 2>/dev/null && ! grep -q "SKILL_DIR=" "${dst}" 2>/dev/null; then
      cp "${src}" "${dst}"
      chmod +x "${dst}" || true
      echo "[ok] refreshed wrapper: ${dst}" >&2
    fi
  fi
done

mkdir -p "${WORKSPACE}"
cat >"${MARKER}" <<EOF
This directory is a local research-team skill self-evolution workspace.
Generated by: ${SCRIPT_DIR}/init_skilldev_workspace.sh
EOF

CFG="${WORKSPACE}/research_team_config.json"
if [[ -f "${CFG}" ]]; then
  python3 - "${CFG}" "${STAGE}" <<'PY'
from __future__ import annotations

import json
import sys
from pathlib import Path

path = Path(sys.argv[1])
stage = str(sys.argv[2]).strip().lower()
if stage not in ("exploration", "development", "publication"):
    stage = "development"

data = json.loads(path.read_text(encoding="utf-8", errors="replace"))
if not isinstance(data, dict):
    data = {}
data["project_stage"] = stage
path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
print("[ok] patched:", path)
PY
fi

if [[ "${SKIP_DEMO}" -ne 1 ]]; then
  bash "${SKILL_ROOT}/scripts/bin/generate_demo_milestone.sh" --root "${WORKSPACE}" --tag "${TAG}" --force
fi

CHARTER="${WORKSPACE}/project_charter.md"
if [[ -f "${CHARTER}" ]]; then
  PROFILE_FOR_CHARTER="${PROFILE}"
  python3 - "${CHARTER}" "${PROFILE_FOR_CHARTER}" <<'PY'
from __future__ import annotations

import re
import sys
from pathlib import Path

path = Path(sys.argv[1])
profile = str(sys.argv[2] or "").strip() or "methodology_dev"

text = path.read_text(encoding="utf-8", errors="replace").replace("\r\n", "\n").replace("\r", "\n")

def sub_line(pat: str, repl: str) -> None:
    global text
    text = re.sub(pat, repl, text, flags=re.MULTILINE)

sub_line(r"^Status:\s*.*$", "Status: APPROVED")
sub_line(r"^Primary goal:\s*.*$", "Primary goal: Improve the research-team skill via a reproducible, auditable self-evolution workspace")
sub_line(
    r"^Validation goal\(s\):\s*.*$",
    "Validation goal(s): Run deterministic self-audit (preflight-only + smoke tests) and keep docs/contracts aligned with real research workflows",
)
sub_line(r"^Declared profile:\s*.*$", f"Declared profile: {profile}")
sub_line(r"^Rationale:\s*.*$", "Rationale: This is methodology/tooling development for the skill itself (not a user research project).")

text = re.sub(
    r"(^Anti-goals / non-goals.*\n)(?:[-*+]\s+.*\n)+",
    r"\1- Do NOT introduce hard cutoffs that break real research workflows; prefer warn+debt in exploration and enforce in development/publication.\n",
    text,
    flags=re.MULTILINE,
)

commitments_block = (
    "Project-specific commitments (fill at least 2 bullets; must include at least 1 KB link):\n"
    "- [KB] Keep an auditable query/decision trail: [demo_trace](knowledge_base/methodology_traces/demo_trace.md)\n"
    "- [DOC] Keep docs/templates aligned with gates and agent-first usage; record any policy exceptions in KB traces.\n"
)
text = re.sub(
    r"^Project-specific commitments \(fill at least 2 bullets; must include at least 1 KB link\):\n(?:[-*+]\s+.*\n)+",
    commitments_block,
    text,
    flags=re.MULTILINE,
)

text = re.sub(
    r"^\s*-\s*Allowed\s+sources\s+for\s+discovery\s*:\s*.*$",
    "- Allowed sources for discovery: prefer stable anchors (INSPIRE/arXiv/DOI/GitHub) + official docs/archives; general scholarly search is OK for discovery if logged in KB traces and stabilized to final anchors.",
    text,
    flags=re.MULTILINE,
)

path.write_text(text.rstrip() + "\n", encoding="utf-8")
print("[ok] patched:", path)
PY
fi

echo "[ok] skilldev workspace ready: ${WORKSPACE}" >&2
echo "[ok] stage=${STAGE} profile=${PROFILE} tag=${TAG}" >&2
