$pdf_mode = 1;
$pdflatex = 'pdflatex -interaction=nonstopmode -synctex=1 %O %S';
$bibtex = 'bibtex %O %B';

# RevTeX projects typically benefit from a full clean list.
$clean_ext = 'bbl blg fdb_latexmk fls synctex.gz run.xml bcf';
