from __future__ import annotations

from .project_contracts_bridge import load_project_contracts_module


_module = load_project_contracts_module("project_surface")

PROJECT_CHARTER = _module.PROJECT_CHARTER
PROJECT_INDEX = _module.PROJECT_INDEX
RESEARCH_PLAN = _module.RESEARCH_PLAN
RESEARCH_NOTEBOOK = _module.RESEARCH_NOTEBOOK
RESEARCH_CONTRACT = _module.RESEARCH_CONTRACT
SCAFFOLD_SUPPORT_FILES = _module.SCAFFOLD_SUPPORT_FILES
SCAFFOLD_ROOT_FILES = _module.SCAFFOLD_ROOT_FILES
SCAFFOLD_TEMPLATE_FILES = _module.SCAFFOLD_TEMPLATE_FILES
SCAFFOLD_CONTEXT_FILES = _module.SCAFFOLD_CONTEXT_FILES
SCAFFOLD_TEMPLATE_MAP = _module.SCAFFOLD_TEMPLATE_MAP
NamingAuditDecision = _module.NamingAuditDecision
BOUNDARY_NAMING_AUDIT = _module.BOUNDARY_NAMING_AUDIT
