from __future__ import annotations

from .project_contracts_bridge import load_project_contracts_module


_module = load_project_contracts_module("project_surface")

PROJECT_CHARTER = _module.PROJECT_CHARTER
PROJECT_INDEX = _module.PROJECT_INDEX
RESEARCH_PLAN = _module.RESEARCH_PLAN
RESEARCH_NOTEBOOK = _module.RESEARCH_NOTEBOOK
RESEARCH_CONTRACT = _module.RESEARCH_CONTRACT
RESEARCH_PREFLIGHT = _module.RESEARCH_PREFLIGHT
PROJECT_BRIEF = _module.PROJECT_BRIEF
IDEA_LOG = _module.IDEA_LOG
MCP_CONFIG_EXAMPLE = _module.MCP_CONFIG_EXAMPLE
SCAFFOLD_SUPPORT_FILES = _module.SCAFFOLD_SUPPORT_FILES
MINIMAL_ROOT_FILES = _module.MINIMAL_ROOT_FILES
FULL_ROOT_FILES = _module.FULL_ROOT_FILES
MINIMAL_TEMPLATE_FILES = _module.MINIMAL_TEMPLATE_FILES
FULL_TEMPLATE_FILES = _module.FULL_TEMPLATE_FILES
MINIMAL_CONTEXT_FILES = _module.MINIMAL_CONTEXT_FILES
SCAFFOLD_TEMPLATE_MAP = _module.SCAFFOLD_TEMPLATE_MAP
NamingAuditDecision = _module.NamingAuditDecision
BOUNDARY_NAMING_AUDIT = _module.BOUNDARY_NAMING_AUDIT
